# Generated by Django 6.0.4 on 2026-05-03 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=2)),
                ("owm_city_id", models.IntegerField(unique=True)),
                ("last_queried", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("name", "country_code")},
            },
        ),
        migrations.CreateModel(
            name="CurrentWeather",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("temp_c", models.FloatField()),
                ("feels_like_c", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("wind_speed_ms", models.FloatField()),
                ("condition", models.CharField(max_length=50)),
                ("condition_icon", models.CharField(max_length=10)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="current", to="weather.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForecastDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("temp_high_c", models.FloatField()),
                ("temp_low_c", models.FloatField()),
                ("condition", models.CharField(max_length=50)),
                ("condition_icon", models.CharField(max_length=10)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forecast_days", to="weather.location"
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("location", "date")},
            },
        ),
    ]
