# Generated by Django 6.0.4 on 2026-05-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="owm_city_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
