# Generated by Django 6.0.4 on 2026-05-24 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_location_latitude_location_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentweather",
            name="fetched_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="forecastday",
            name="fetched_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "search_type",
                    models.CharField(choices=[("city", "City"), ("coordinates", "Coordinates")], max_length=20),
                ),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="searches", to="weather.location"
                    ),
                ),
            ],
            options={
                "ordering": ["-searched_at"],
            },
        ),
    ]
